   
for zsh_source in $HOME/.zsh/configs/**/*.zsh; do
  source $zsh_source
done


export ZSH=~/.oh-my-zsh

ZSH_THEME="robbyrussell"

 plugins=(git)

source $ZSH/oh-my-zsh.sh

_not_inside_tmux() { [[ -z "$TMUX" ]] }

ensure_tmux_is_running() {
  if _not_inside_tmux; then
   ~/tat.sh
  fi
}

ensure_tmux_is_running

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# General ZSH configurations

export EDITOR="vim"

sz() { source ~/.zshrc }
bindkey -v

export PATH=$PATH:/home/eduardoborsa/programs/clang_Build/bin/
