export ZSH=~/.oh-my-zsh
ZSH_THEME="robbyrussell"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

export PATH=$PATH:~/programs/node/bin/
export PATH=$PATH:~/programs/chromedriver_linux64/
alias vim='nvim'
alias v='nvim'
alias ctags="ctags -R --exclude=.git --exclude=node_modules --exclude=test --exclude=deps"
alias youtube-dl="youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4"
alias youtube-dl-audio="youtube-dl -f 'bestaudio[ext=m4a]/mp4'"

_not_inside_tmux() { [[ -z "$TMUX" ]] }

ensure_tmux_is_running() {
  if _not_inside_tmux; then
   ~/programs/dotFiles/bin/tat.sh
  fi
}

ensure_tmux_is_running

export EDITOR="nvim"
# To set vim in terminal
bindkey -v
bindkey '^R' history-incremental-search-backward
export KEYTIMEOUT=1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"


# Theme
base16_tomorrow-night
# FZF config to exlude the same seeting as Ag
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_DEFAULT_COMMAND='ag --ignore android --ignore ios -g ""'

bindkey '^ ' autosuggest-accept

source ~/programs/dotFiles/zsh/configs/functions.zsh

. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

# export JAVA_HOME='/home/dado/programs/jre-8u111-linux-x64/jre1.8.0_111/'
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

setxkbmap -option ctrl:swapcaps
